server:
  port: 8080
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: FXTravel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://fx-mysql-service:3306/fx_db?allowPublicKeyRetrieval=true&useSSL=false
    username: 'root'
    password: 'yyyYYY&0121'
    hikari:
      username: 'root'
      password: 'yyyYYY&0121'
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 3000
      minimum-idle: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  mail:
    host: smtp.qq.com           # 邮件服务器
    port: 587
    username: 2137233787@qq.com
    password: sqnktakdreyuifjh  # 不是邮箱密码，是“应用专用密码”
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  graphql:
    cors:
      allow-credentials: true
      allowed-headers: '*'
      allowed-origins:
        [
          'http://localhost:5173/',
          'http://10.193.185.196:5173/',
          'http://fx-frontend:80',
          'http://fx-frontend-service:80',
          '*'
        ]
      allowed-methods: ['GET','POST','DELETE','PUT','OPTIONS']