server:
  port: 8080
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: FXTravel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fxtravel_g14?serverTimezone=UTC
    # url: jdbc:mysql://localhost:3306/fxtravel_g14?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
    username: 'root'
    password: 'ehern030121'
    hikari:
      username: 'root'
      password: 'ehern030121'
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 3000
      minimum-idle: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  mail:
    host: smtp.qq.com           # 邮件服务器
    port: 587
    username: 2137233787@qq.com
    password: sqnktakdreyuifjh  # 不是邮箱密码，是“应用专用密码”
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true