server:
  port: 8080
spring:
  application:
    name: FXTravel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/fxtravel_g14?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/fxtravel_g14?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&autoReconnect=true
    username: 'root'
    password: 'yyyYYY&0121'
    hikari:
      username: 'root'
      password: 'yyyYYY&0121'
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 3000
      minimum-idle: 10
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update