apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fx-g14
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never  # 使用本地构建的镜像
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: fx-g14
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
