name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '18'
#          cache: 'npm'
#          cache-dependency-path: frontend/package-lock.json
#
#      - name: Install frontend dependencies
#        working-directory: ./frontend
#        run: npm ci
#
#      - name: Run frontend tests
#        working-directory: ./frontend
#        run: npm run test:run

  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest changes
        shell: bash
        run: |
          cd "D:\Datas\repo\FXSpringboot"
          git checkout master
          git pull origin master

      - name: Execute Deployment Script
        shell: bash
        run: |
          cd "D:\Datas\repo\FXSpringboot"
          ./deploy.sh